[project]
name = "basic-pp"
version = "0.0.0"
authors = [
  { name="R A Veeraragavan", email="veeracoder123@gmail.com" },
]
description = "a simple language for begginers."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pdoc3>=0.11.6",
    "pytest>=9.0.3",
    "rich>=15.0.0",
    "zensical>=0.0.43",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/veeracoder508/e2eeftp"
Issues = "https://github.com/veeracoder508/e2eeftp/issues"

[tool.uv.workspace]
members = [
    ".",
    ".",
]

[tool.uv.sources]
basic-pp = { workspace = true }

[dependency-groups]
dev = [
    "basic-pp",
]

[project.scripts]
bpp = "basicpp.cli:cli"

[tool.setuptools.packages.find]
where = ["src"]